# -*- coding: utf-8 -*-
"""Concat_format()_f-strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BwPFq-LGIwq0bK6ygfRB-kA_tKHHUHM9

"The Mau Forest is the largest closed‐canopy montane forest ecosystem in East Africa, covering 400000 hectares."
"""

# Given the following variables
forest_name = "Mau Forest"
area = 400000
forest_type = "closed‐canopy montane"

# Insert code here
print("The " + forest_name + " is the largest " + forest_type + " forest ecosystem in East Africa, covering", area,  "hectares.")

""" "The annual growth rate of trees in the Amazon forest is 2.5%."

"""

# Given the following variables
growth_rate = 2.5
forest_region = "Amazon"

# Insert code here
formatted_string="The annual growth rate of trees in the {} forest is {}%".format(forest_region,growth_rate)
formatted_string

""""Sustainable Forest Management is crucial for maintaining biodiversity."
"""

# Given the following variables
sfm_concept = "Sustainable Forest Management"
biodiversity_importance = "maintaining biodiversity"

# Insert code here
formatted_string=f"{sfm_concept} is crucial for {biodiversity_importance}"
formatted_string